# Generated by Django 4.0.5 on 2022-06-21 21:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editier2api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobFlow', models.CharField(max_length=50)),
                ('intervalTime', models.FloatField()),
                ('jobName', models.CharField(max_length=50)),
                ('countryCode', models.CharField(max_length=10)),
                ('created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
