# Generated by Django 4.0.5 on 2022-06-21 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editier2api', '0002_jobflow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobflow',
            old_name='jobFlow',
            new_name='jobFlowName',
        ),
    ]
